<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/db.php';

$db = Database::getInstance();

$activeRules = $db->fetchAll("
    SELECT * FROM automation_rules 
    WHERE is_active = true 
    AND (last_executed IS NULL OR last_executed < (CURRENT_TIMESTAMP - INTERVAL '1 hour'))
");

foreach ($activeRules as $rule) {
    try {
        $triggerConfig = json_decode($rule['trigger_config'], true) ?? [];
        $actionConfig = json_decode($rule['action_config'], true) ?? [];
        
        $shouldExecute = false;
        $executionDetails = [];
        
        switch ($rule['trigger_type']) {
            case 'schedule':
                $schedule = $triggerConfig['schedule'] ?? 'daily';
                $targetTime = $triggerConfig['time'] ?? '09:00';
                $currentHour = date('H:i');
                
                if ($schedule === 'daily') {
                    $lastExec = $rule['last_executed'] ? date('Y-m-d', strtotime($rule['last_executed'])) : null;
                    $today = date('Y-m-d');
                    
                    if ($lastExec !== $today && $currentHour >= substr($targetTime, 0, 5)) {
                        $shouldExecute = true;
                        $executionDetails['trigger_reason'] = "Daily schedule at {$targetTime}";
                    }
                } elseif ($schedule === 'hourly') {
                    $shouldExecute = true;
                    $executionDetails['trigger_reason'] = "Hourly schedule";
                } elseif ($schedule === 'weekly') {
                    $targetDay = $triggerConfig['day'] ?? 'monday';
                    if (strtolower(date('l')) === $targetDay) {
                        $shouldExecute = true;
                        $executionDetails['trigger_reason'] = "Weekly schedule on {$targetDay}";
                    }
                }
                break;
                
            case 'event':
                $shouldExecute = false;
                $executionDetails['trigger_reason'] = "Event-based trigger (requires external event)";
                break;
                
            case 'condition':
                $conditionField = $triggerConfig['field'] ?? null;
                $conditionOperator = $triggerConfig['operator'] ?? null;
                $conditionValue = $triggerConfig['value'] ?? null;
                
                if ($conditionField && $conditionOperator && $conditionValue !== null) {
                    $shouldExecute = true;
                    $executionDetails['trigger_reason'] = "Condition: {$conditionField} {$conditionOperator} {$conditionValue}";
                }
                break;
                
            default:
                $shouldExecute = false;
                $executionDetails['trigger_reason'] = "Unknown trigger type";
        }
        
        if ($shouldExecute) {
            $actionSuccess = false;
            $actionResult = [];
            
            switch ($rule['action_type']) {
                case 'create_task':
                    $taskTitle = $actionConfig['task_title'] ?? "Automated Task from {$rule['rule_name']}";
                    $taskDescription = $actionConfig['task_description'] ?? "Auto-generated by automation rule";
                    
                    try {
                        $taskId = $db->insert('tasks', [
                            'user_id' => $rule['user_id'],
                            'title' => $taskTitle,
                            'description' => $taskDescription,
                            'status' => 'pending',
                            'priority' => $actionConfig['priority'] ?? 'medium'
                        ]);
                        
                        $actionSuccess = true;
                        $actionResult['task_id'] = $taskId;
                        $actionResult['message'] = "Created task: {$taskTitle}";
                    } catch (Exception $e) {
                        $actionResult['error'] = "Failed to create task: " . $e->getMessage();
                    }
                    break;
                    
                case 'send_notification':
                    $notifTitle = $actionConfig['title'] ?? "Notification from {$rule['rule_name']}";
                    $notifMessage = $actionConfig['message'] ?? "Automated notification";
                    
                    try {
                        $notifId = $db->insert('notifications', [
                            'user_id' => $rule['user_id'],
                            'title' => $notifTitle,
                            'message' => $notifMessage,
                            'is_read' => false,
                            'notification_type' => 'automation'
                        ]);
                        
                        $actionSuccess = true;
                        $actionResult['notification_id'] = $notifId;
                        $actionResult['message'] = "Sent notification: {$notifTitle}";
                    } catch (Exception $e) {
                        $actionResult['error'] = "Failed to send notification: " . $e->getMessage();
                    }
                    break;
                    
                case 'log_journal':
                    $journalTitle = $actionConfig['title'] ?? "Automated Journal Entry";
                    $journalContent = $actionConfig['content'] ?? "Auto-generated entry from automation";
                    
                    try {
                        $entryId = $db->insert('journal_entries', [
                            'user_id' => $rule['user_id'],
                            'entry_date' => date('Y-m-d'),
                            'title' => $journalTitle,
                            'content' => $journalContent,
                            'entry_type' => 'text'
                        ]);
                        
                        $actionSuccess = true;
                        $actionResult['entry_id'] = $entryId;
                        $actionResult['message'] = "Created journal entry: {$journalTitle}";
                    } catch (Exception $e) {
                        $actionResult['error'] = "Failed to create journal entry: " . $e->getMessage();
                    }
                    break;
                    
                default:
                    $actionResult['message'] = "Action type '{$rule['action_type']}' executed (placeholder)";
                    $actionSuccess = true;
            }
            
            $executionResult = array_merge([
                'status' => $actionSuccess ? 'executed' : 'failed',
                'timestamp' => date('Y-m-d H:i:s'),
                'action_type' => $rule['action_type'],
                'trigger_type' => $rule['trigger_type']
            ], $executionDetails, $actionResult);
            
            $db->insert('automation_logs', [
                'rule_id' => $rule['id'],
                'user_id' => $rule['user_id'],
                'execution_result' => json_encode($executionResult),
                'executed_successfully' => $actionSuccess
            ]);
            
            $db->query("
                UPDATE automation_rules 
                SET last_executed = CURRENT_TIMESTAMP, execution_count = execution_count + 1 
                WHERE id = ?
            ", [$rule['id']]);
            
            echo "Executed rule: {$rule['rule_name']} - " . ($actionSuccess ? 'SUCCESS' : 'FAILED') . "\n";
        } else {
            echo "Skipped rule: {$rule['rule_name']} - Trigger conditions not met\n";
        }
        
    } catch (Exception $e) {
        error_log("Automation executor error for rule {$rule['id']}: " . $e->getMessage());
        
        $db->insert('automation_logs', [
            'rule_id' => $rule['id'],
            'user_id' => $rule['user_id'],
            'execution_result' => json_encode(['error' => $e->getMessage()]),
            'executed_successfully' => false
        ]);
    }
}

echo "Automation executor completed. Processed " . count($activeRules) . " rules.\n";
